# Generated by Django 5.1.6 on 2025-02-12 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='custom_months_interval',
            field=models.IntegerField(blank=True, help_text='Number of months between occurrences', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='income',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='custom_days',
            field=models.IntegerField(blank=True, help_text='Day of month for custom recurrence (1-31)', null=True),
        ),
        migrations.CreateModel(
            name='ExpenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='expenses.expense')),
            ],
            options={
                'ordering': ['-changed_date'],
            },
        ),
        migrations.CreateModel(
            name='IncomeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateField()),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='expenses.income')),
            ],
            options={
                'ordering': ['-changed_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='expenses.expense')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('expense', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IncomeException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='expenses.income')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('income', 'date')},
            },
        ),
    ]
