# Generated by Django 5.1.6 on 2025-02-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('recurrence_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('custom', 'Custom Days')], default='monthly', max_length=20)),
                ('custom_days', models.IntegerField(blank=True, help_text='Days between occurrences for custom recurrence', null=True)),
                ('occurrences', models.IntegerField(blank=True, help_text='Number of occurrences if end_date not specified', null=True)),
                ('tag', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_type', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('custom', 'Custom Days')], default='monthly', max_length=20, null=True)),
                ('tag', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
